name: CI K8s Dev

run-name: "[K8S] Build and push trp-ui:dev"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  build-and-push:
    uses: lidofinance/actions/.github/workflows/k8s-build-push-harbor.yml@c7b5b6c5d8013046347d728d748fa741eb214e28
    with:
      tag: dev
      registry: registry.dev.k8s-dev.org
      registry_username: robot$team-daotech-rw
      image: team-daotech/trp-ui
      environment: harbor_dev_release
    secrets:
      registry_token: ${{ secrets.HARBOR_ROBOT_TOKEN }}
