name: CI Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions: {}

jobs:
  deploy:
    if: ${{ github.repository != 'lidofinance/lido-frontend-template' }}
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Staging deploy
        uses: lidofinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: 'lidofinance/infra-mainnet'
          TARGET_WORKFLOW: 'deploy_staging_mainnet_trp-ui.yaml'
          TARGET: 'main'
